### ISSUE TITLE
UI: Login-Page

### ISSUE THREAD

**Issue by NavneetKumar2907** [NavneetKumar2907/Sankalan#1]
Only Create the Layout File inside layout folder.
Dimensions and values have to be fetched from dimens.xml file.
![loginMain](https://user-images.githubusercontent.com/76484161/161888930-d80c9da6-6ad3-43ac-865e-efc7eff81313.JPG)

**Comment by abhishek-gupta-ducs** [comment]
Abhishek Gupta
