### ISSUE TITLE
UI: HomeScreen_EventList

### ISSUE THREAD

**Issue by NavneetKumar2907** [NavneetKumar2907/Sankalan#3]
Only Create the Layout File inside layout folder.
Dimensions and values have to be fetched from dimens.xml file.
For Recycle View Separate custom file have to be created.
HomeScreen Layout contains fragment so main 
It contains two layout one with recycleView and second with custome layout of recycleView.

![home_screen_event_list](https://user-images.githubusercontent.com/76484161/161889260-8c98723c-ed35-4c82-ac9e-ec6e4d089ef4.JPG)

**Comment by RishiSingh00** [comment]
Rishi
