### ISSUE TITLE
UI:Forgot_Password

### ISSUE THREAD

**Issue by NavneetKumar2907** [NavneetKumar2907/Sankalan#4]
Only Create the Layout File inside layout folder.
Dimensions and values have to be fetched from dimens.xml file.

**Don't Create the New Password line and login button**

![forgot](https://user-images.githubusercontent.com/76484161/161888812-7fd07ecc-617d-4336-92d7-23a1c55e80e8.JPG)

**Comment by abhishek-gupta-ducs** [comment]
Abhishek Gupta
